### ISSUE TITLE
Dependencies broken

### ISSUE THREAD

**Issue by kyle-wedgwood** [delunapaolo/calipy#1]
Cannot install calipy from either existing or new Anaconda build. Tested on MacOS Sierra 10.12.6

**Comment by delunapaolo** [comment]
I removed the dependency on pyqtgraph, which threw the error you probably referred to.

Let me know if your problem is now fixed.

**Comment by kyle-wedgwood** [comment]
I still have the same error. Traceback as follows:

Traceback (most recent call last):
  File "//anaconda2/envs/calipy/lib/python3.6/site-packages/numpy/core/__init__.py", line 16, in <module>
    from . import multiarray
ImportError: dlopen(//anaconda2/envs/calipy/lib/python3.6/site-packages/numpy/core/multiarray.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libopenblas.dylib
  Referenced from: //anaconda2/envs/calipy/lib/python3.6/site-packages/numpy/core/multiarray.cpython-36m-darwin.so
  Reason: no suitable image found.  Did find:
	/usr/local/lib/libopenblas.dylib: stat() failed with errno=13

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/calipy/_run.py", line 6, in <module>
    import numpy as np
  File "//anaconda2/envs/calipy/lib/python3.6/site-packages/numpy/__init__.py", line 142, in <module>
    from . import add_newdocs
  File "//anaconda2/envs/calipy/lib/python3.6/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "//anaconda2/envs/calipy/lib/python3.6/site-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "//anaconda2/envs/calipy/lib/python3.6/site-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "//anaconda2/envs/calipy/lib/python3.6/site-packages/numpy/core/__init__.py", line 26, in <module>
    raise ImportError(msg)
ImportError: 
Importing the multiarray numpy extension module failed.  Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try `git clean -xdf` (removes all
files not under version control).  Otherwise reinstall numpy.

Original error was: dlopen(//anaconda2/envs/calipy/lib/python3.6/site-packages/numpy/core/multiarray.cpython-36m-darwin.so, 2): Library not loaded: @rpath/libopenblas.dylib
  Referenced from: //anaconda2/envs/calipy/lib/python3.6/site-packages/numpy/core/multiarray.cpython-36m-darwin.so
  Reason: no suitable image found.  Did find:
	/usr/local/lib/libopenblas.dylib: stat() failed with errno=13

**Comment by delunapaolo** [comment]
Apparently, the problem is not related to my repo, but the error message says:
`Importing the multiarray numpy extension module failed. Most
likely you are trying to import a failed build of numpy.
If you're working with a numpy git repo, try git clean -xdf (removes all
files not under version control). Otherwise reinstall numpy.`

The error is raised on `File "src/calipy/_run.py", line 6, in
import numpy as np`

---
You said that you have tried on a new Anaconda build, which I guess it means on a newly created environment. In that case, please open Anaconda Navigator, create a new environment, install numpy in it and try to import it in a script. Let me know if you need a step-by-step guide about it. 

In case you still get an error, I suppose it is something to do with your machine (since it works for me as of today on several MacOS and Windows systems). Otherwise, we'll have to see if there is some sort of installation issue during the creation of the environment.

**Comment by kyle-wedgwood** [comment]
Do you mean to install a new numpy in the calipy environment or to make an entirely new one just for numpy?

**Comment by delunapaolo** [comment]
Please try in a new environment where you’ll install only python 3.6.6 and numpy 1.15.4 (these are the versions used by the repo). Then, create a script with the following lines:

`
import numpy as np; print(np.__version__)
`

run it and check whether you get an error, or you get printed the numpy version you installed.

**Comment by kyle-wedgwood** [comment]
Ok, have run:
$ conda create -n numpy_build python=3.6.6 numpy=1.15.4

to create the environment. Have they run script as suggested. Output is:

$ Error in sitecustomize; set PYTHONVERBOSE for traceback:
$ KeyError: 'PYTHONPATH'
$ 1.15.4

I guess something is messed up with my python path...

**Comment by delunapaolo** [comment]
I can suggest the following approaches to find out what the problem is:

1. Make sure you activated the environment before running the script. If you are working from the terminal, run `conda activate numpy_build`, and then you'll run the script to test numpy's installation.

2. Make sure that python is reachable from the terminal, by simply typing `python`. Also try activating the numpy_build environment and then run `python`. If you can complete all these steps, I'd assume it is not a problem related to Anaconda or python, but rather numpy.

3. Reinstall Anaconda, downloading the [latest graphical installer for macOS](https://www.anaconda.com/distribution/#macos), but make sure that the following box is ticked during the installation:
<img width="622" alt="image" src="https://user-images.githubusercontent.com/12517451/68192669-f5d23880-ffb1-11e9-82c9-143f0f33a29e.png">

4. Create the numpy_build environment once more, with only python installed. Then, try to [install numpy via pip](https://www.scipy.org/install.html#pip-install), to circumvent any problem that is related to Anaconda, and try again running the sample script which should print numpy's version.

<hr>

I'll close this issue, as it is not related to my repo, but feel free to write again in case you have specific problems with it.
